# fly.toml app configuration file generated for weekly-meals-be on 2024-10-31T23:34:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weekly-meals-be'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
